// generateReadme function that creats the README.md file
function generateReadme(answers) {
    return `
    ## projectTitle
${answers.projectTitle} 
  
![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />
## Description
 ${answers.description}
## Table of Contents
- [Description](#description)
- [Installation](#installation)
- [Usage](#usage)
- [License](#license)
- [Contributing](#contributing)
- [Tests](#tests)
- [Questions](#questions)
## Installation
 ${answers.installation}
## Usage
${answers.usage}
## License
![badge](https://img.shields.io/badge/license-${answers.license}-darkblue)
<br />
This application is covered by the ${answers.license} license. 
## Contributing
${answers.contributing}
## Tests
✏️ ${answers.tests}
## Questions
 ${answers.questions}<br />
<br />
:octocat: Find me on GitHub: [${answers.username}](https://github.com/${answers.username})<br />
<br />
✉️ Reach out to me with any questions @: ${answers.email}<br /><br />
_This README was generated by [README-generator](https://github.com/samuelsholib/cool-Looking-README)_
    `;
}

module.exports = generateReadme;